name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4        
        with:
          version: 9
          run_install: false

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type-check
        run: pnpm type-check

      - name: Run linter
        run: pnpm lint

      - name: Integration tests
        run: pnpm test -- --coverage

      # DEPENDENCY ANALISYS npm audit --production npm outdated
      # SEC CHECKS
      # UNITY TESTS/INTEGRATION TESTS
      # SONAR
      # https://coderabbit.ai/#pricing
      # PREVIEW BUILD
